Use channel map in TPG
DUNE-DAQ/fdreadoutlibs pull request #2
Opened 2022-02-07 12:01 UTC by philiprodrigues

This PR adds use of the channel map to the software TPG. It's a manual forward-port of the same changes that were made on the 2.8.2 readout release for the VD coldbox tests in December. This PR depends on https://github.com/DUNE-DAQ/readoutlibs/pull/6 . So far, it builds but isn't tested. Before I do some serious testing, I'd like to get a check that I've put the code in the right place in the new readout-package structure.

2022-02-07 16:00 UTC, roland-sipos requested changes

2022-02-07 16:00 UTC, roland-sipos commented on include/fdreadoutlibs/wib/tpg/RegisterToChannelNumber.hpp
> +#ifndef READOUT_SRC_WIB_TPG_REGISTERTOCHANNELNUMBER_HPP_
Please update the include guard.

2022-02-07 21:05 UTC, roland-sipos commented
Also, could you please have a look on why the CI fails?

`/__w/fdreadoutlibs/fdreadoutlibs/dev-c7/sourcecode/fdreadoutlibs/include/fdreadoutlibs/wib/WIBFrameProcessor.hpp:226:64: error: ‘struct dunedaq::readoutlibs::readoutconfig::RawDataProcessorConf’ has no member named ‘channel_map_name’; did you mean ‘channel_map_rce’?`

2022-02-09 14:38 UTC, philiprodrigues commented
I think the CI failure is because the CI doesn't have https://github.com/DUNE-DAQ/readoutlibs/pull/6 merged, which is what provides new variable that's needed. I'm not sure of the best way to deal with that

2022-02-21 15:18 UTC, roland-sipos commented
Hi @philiprodrigues ! Indeed this was not merged in yet, doing it right now.

2022-02-21 15:20 UTC, roland-sipos approved these changes

2022-02-21 15:20 UTC, merged